export const SWAP_CURRENCY = 'SWAP_CURRENCY'
export const CHANGE_CURRENCY_AMOUNT = 'CHANGE_CURRENCY_AMOUNT'

export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY'
export const CHANGE_QUOTE_CURRENCY = 'CHANGE_QUOTE_CURRENCY'

export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR'

export const GET_INTIAL_CONVERSION = 'GET_INTIAL_CONVERSION'

export const CONVERSION_RESULT = 'CONVERSION_RESULT'
export const CONVERSION_ERROR = 'CONVERSION ERROR'
